# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Palm-Treo680MessagesDB
version:      1.0
version_from: lib/Palm/Treo680MessagesDB.pm
installdirs:  site
requires:
    Data::Hexdumper:               0
    DateTime:                      0.3
    Palm::PDB:                     1.29
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
